Repository nasa-gibs/worldview, pull requests merged in 2018-08, with the labels that each got.

#1176 Fix configuration build
  tasks/config.js
Labels: under development

#1179 v2.7.1
  package-lock.json
  package.json
Labels: under development

#1185 updated about section
  web/pages/about.html
Labels: ready for review

#1200 Change tour to not scroll
  web/js/tour.js
Labels: under development

#1203 Override JQuery UI style for map buttons
  web/css/jquery-ui-override.css
Labels: under development

#1208 Use today for end date in active layers
  web/js/layers/model.js
Labels: under development

#1218 Remove time adjustment for general case in favor of when needed
  web/js/util/util.js
Labels: under development

#1217 Truncate selected date to UTC midnight when not subdaily
  web/js/map/layerbuilder.js
Labels: bug, under development

#1220 Remove unneeded style
  web/css/mobile.css
Labels: under development

#1209 Fix state rotation parameter when switching projections
  web/js/map/ui.js
Labels: under development

#1223 Python-virtualenv build fix
  README.md
  package.json
  tasks/pythonInstall.sh
Labels: under development

#1226 Fix gif bug not displaying the last 3 days of imagery
  tasks/validateOptions.py
Labels: under development
