Repository nasa-gibs/worldview, pull requests merged in 2018-06, with the labels that each got.

#1039 v2.5.1
  package-lock.json
  package.json
Labels: under development

#1020 Remove unneeded font formats & add compressed files
  web/css/fonts.css
  web/font/OpenSans/Bold/OpenSans-Bold.eot
  web/font/OpenSans/Bold/OpenSans-Bold.svg
  web/font/OpenSans/Bold/OpenSans-Bold.ttf
  web/font/OpenSans/Bold/OpenSans-Bold.woff
  web/font/OpenSans/Bold/OpenSans-Bold.woff2
  web/font/OpenSans/BoldItalic/OpenSans-BoldItalic.eot
  web/font/OpenSans/BoldItalic/OpenSans-BoldItalic.svg
  web/font/OpenSans/BoldItalic/OpenSans-BoldItalic.ttf
  web/font/OpenSans/BoldItalic/OpenSans-BoldItalic.woff
  web/font/OpenSans/BoldItalic/OpenSans-BoldItalic.woff2
  web/font/OpenSans/Italic/OpenSans-Italic.eot
  web/font/OpenSans/Italic/OpenSans-Italic.svg
  web/font/OpenSans/Italic/OpenSans-Italic.ttf
  web/font/OpenSans/Italic/OpenSans-Italic.woff
  web/font/OpenSans/Italic/OpenSans-Italic.woff2
  web/font/OpenSans/Light/OpenSans-Light.eot
  web/font/OpenSans/Light/OpenSans-Light.svg
  web/font/OpenSans/Light/OpenSans-Light.ttf
  web/font/OpenSans/Light/OpenSans-Light.woff
  web/font/OpenSans/Light/OpenSans-Light.woff2
  web/font/OpenSans/LightItalic/OpenSans-LightItalic.eot
  web/font/OpenSans/LightItalic/OpenSans-LightItalic.svg
  web/font/OpenSans/LightItalic/OpenSans-LightItalic.ttf
  web/font/OpenSans/LightItalic/OpenSans-LightItalic.woff
  web/font/OpenSans/LightItalic/OpenSans-LightItalic.woff2
  web/font/OpenSans/Regular/OpenSans-Regular.eot
  web/font/OpenSans/Regular/OpenSans-Regular.svg
  web/font/OpenSans/Regular/OpenSans-Regular.ttf
  web/font/OpenSans/Regular/OpenSans-Regular.woff
  web/font/OpenSans/Regular/OpenSans-Regular.woff2
  web/font/RobotoMono/Regular/RobotoMono-Regular.eot
  web/font/RobotoMono/Regular/RobotoMono-Regular.svg
  web/font/RobotoMono/Regular/RobotoMono-Regular.ttf
  web/fonts/OpenSans/Bold/OpenSans-Bold.eot
  web/fonts/OpenSans/Bold/OpenSans-Bold.ttf
  web/fonts/OpenSans/Bold/OpenSans-Bold.woff
  web/fonts/OpenSans/BoldItalic/OpenSans-BoldItalic.eot
  web/fonts/OpenSans/BoldItalic/OpenSans-BoldItalic.ttf
  web/fonts/OpenSans/BoldItalic/OpenSans-BoldItalic.woff
  web/fonts/OpenSans/Italic/OpenSans-Italic.eot
  web/fonts/OpenSans/Italic/OpenSans-Italic.ttf
  web/fonts/OpenSans/Italic/OpenSans-Italic.woff
  web/fonts/OpenSans/Light/OpenSans-Light.eot
  web/fonts/OpenSans/Light/OpenSans-Light.ttf
  web/fonts/OpenSans/Light/OpenSans-Light.woff
  web/fonts/OpenSans/LightItalic/OpenSans-LightItalic.eot
  web/fonts/OpenSans/LightItalic/OpenSans-LightItalic.ttf
  web/fonts/OpenSans/LightItalic/OpenSans-LightItalic.woff
  web/fonts/OpenSans/Regular/OpenSans-Regular.eot
  web/fonts/OpenSans/Regular/OpenSans-Regular.ttf
  web/fonts/OpenSans/Regular/OpenSans-Regular.woff
  web/fonts/RobotoMono/Regular/RobotoMono-Regular.eot
  web/fonts/RobotoMono/Regular/RobotoMono-Regular.ttf
  web/fonts/RobotoMono/Regular/RobotoMono-Regular.woff
  web/fonts/RobotoMono/Regular/RobotoMono-Regular.woff2
Labels: ready for review

#1054 Remove e2e tests from travis
  .travis.yml
Labels: under development

#1036 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ready for review

#1056 Remove old issue template
  .github/ISSUE_TEMPLATE.md
Labels: under development

#1047 Fix cut off animation-dragger svg stroke
  web/css/timeline.css
  web/js/date/timeline.js
Labels: bug, under development

#1044 Fix React Dev Tools message flagging dev build and reduce bundle size
  package-lock.json
  package.json
  tasks/buildJS.js
Labels: bug, enhancement, ready for review

#1074 Fix missing bulk download section of data download window
  web/js/data/ui.js
Labels: ready for review

#1071 Add flexbox to fix timeline wrapping bug
  web/css/timeline.css
  web/js/date/timeline.js
Labels: bug, ready for review

#1069 Add space to data download input
  web/css/dataDownload.css
Labels: ready for review

#1059 fix spelling in readme.md
  README.md
Labels: ready for review

#1087 Share Modal Fixes
  web/css/link.css
  web/css/util.css
Labels: ready for review

#1096 Print error if an unknown measurement is found
  web/js/layers/modal.js
Labels: under development

#1083 Timeline width fix 1061
  web/css/timeline.css
  web/js/date/timeline.js
Labels: ready for review

#1081 Fix no 'List All' button in events tab on zoomed in page load
  web/js/natural-events/ui.js
Labels: ready for review

#1101 Fix legend overlap
  tasks/buildCSS.js
  web/css/palettes.css
  web/js/map/runningdata.js
Labels: under development

#1099 Fix panels moving when opened
  web/css/reset.css
Labels: ready for review

#1092 Update tooltip formatting
  web/css/events.css
Labels: bug, ready for review

#1108 remove layer reset for natural events, add zoom fix for polygon types
  web/js/natural-events/ui.js
Labels: ready for review

#1113 Restore title tag colors and boldness in layer descriptions
  web/css/layers.css
Labels: under development

#1116 Fix 0px sidebar padding-bottom causing layer button to move on load
  web/css/products.css
  web/js/layers/sidebar.js
Labels: under development

#1117 add opacity fix to close X in sidebar
  web/css/sidebar-panel.css
Labels: ready for review
