Repository nasa-gibs/worldview, pull requests merged in 2018-09, with the labels that each got.

#1239 v2.8.0
  package-lock.json
  package.json
Labels: under development

#1242 update package-lock.json
  package-lock.json
Labels: bug, under development

#1243 Update package-lock for wvo-rc.3
  package-lock.json
  package.json
Labels: under development

#1248 Fix tour break when used with A|B
  web/js/layers/model.js
  web/js/main.js
  web/js/map/util.js
  web/js/sidebar/ui.js
  web/js/tour.js
Labels: under development

#1249 Fix collapse spacing
  web/js/components/sidebar/collapsed-button.js
Labels: under development

#1253 Fix tour break when not in geographic projection
  web/js/sidebar/ui.js
  web/js/tour.js
Labels: under development

#1255 Fix layer reordering bug that results in losing layers when toggling projections
  web/js/compare/util.js
  web/js/components/sidebar/products/layer-list.js
  web/js/components/sidebar/provider.js
  web/js/components/sidebar/sidebar.js
  web/js/layers/model.js
  web/js/sidebar/ui.js
Labels: under development

#1260 Remove granule download item from dialog #1257
  web/js/data/ui.js
Labels: under development

#1273 Close layer settings on tab change
  web/js/sidebar/ui.js
Labels: ready for review

#1272 Remove extra palette spacing
  web/js/components/sidebar/products/legend.js
Labels: ready for review

#1274 Small Style fixes 1269 1265
  web/css/button.css
  web/js/image/panel.js
Labels: ready for review

#1271 Date selector Adjustments
  web/css/timeline.css
  web/js/components/date-selector/input.js
Labels: ready for review

#1287 Button styling 1276 1281
  web/css/button.css
  web/css/jquery-ui-override.css
  web/css/toolbar.css
Labels: under development

#1291 Fix map shift when clicking on image download
  web/css/sidebar.css
Labels: under development

#1240 Update developing docs
  doc/developing.md
Labels: documentation, ready for review

#1285 Constrain drag-drop to within parent layer-group #1256
  web/css/sidebar-panel.css
  web/js/components/sidebar/products/layer.js
Labels: under development

#1288 Remove dateline dates when in AB
  web/js/components/dateline/text.js
  web/js/map/datelinebuilder.js
Labels: bug, ready for review

#1295 Fix compare styling
  web/css/compare.css
Labels: ready for review, under development

#1301 Make Tab hover border not overlap blue area
  web/css/sidebar.css
Labels: under development

#1300 Fix fuzzy logo
  web/css/sidebar.css
Labels: under development

#1299 Update tour image
  web/images/tour/layer-picker-1.1.png
  web/pages/tour.html
Labels: under development

#1298 Fix A|B draggers touch-event bug
  web/js/components/range-selection/dragger.js
  web/js/date/compare-picks.js
  web/js/util/util.js
Labels: bug, ready for review

#1313 Remove guitar pick when in A|B
  web/js/date/timeline.js
Labels: under development

#1315 Only trigger hasData event if events is active #1314
  web/js/natural-events/request.js
  web/js/sidebar/ui.js
Labels: under development

#1322 Fix Image download coordinate offset
  web/js/image/panel.js
Labels: under development

#1325 Remove dangling apache config link
  README.md
Labels: under development

#1337 Fix polar drag and dropping
  web/css/sidebar.css
  web/js/components/sidebar/products/layer-list.js
  web/js/components/sidebar/products/layer.js
Labels: ready for review

#1340 Sidebar Styling bug fixes
  web/css/sidebar-panel.css
  web/css/sidebar.css
  web/js/components/sidebar/products/layer.js
Labels: ready for review

#1341 Update compare E2E tests to work with UAT/SIT bug fixes
  e2e/features/compare/compare-test.js
Labels: under development

#1350 Add space between Base and Layers #1348
  web/js/components/sidebar/products/products.js
Labels: under development

#1349 Keep layer add button red
  web/js/components/sidebar/footer-content.js
Labels: under development

#1355 v2.9.0
  package-lock.json
  package.json
Labels: under development

#1321 Check that granule to remove has been selected
  web/js/data/map.js
Labels: under development

#1319 Remove 'Events may not be visible at all times' notice when not in events mode
  web/js/natural-events/ui.js
Labels: under development

#1310 Rename id to ident
  tasks/extractConfigFromWMTS.py
Labels: bug, under development

#1309 Sort satellite/sensor list in categories view
  web/js/layers/modal.js
Labels: under development

#1302 Change getCapabilities script to use urllib3
  requirements.txt
  tasks/getCapabilities.py
Labels: ready for review

#1353 Add notificationURL testing parameter and documentation
  doc/testing.md
  web/js/notifications/ui.js
Labels: ready for review

#1230 Add english lang support to HTML document
  web/index.html
Labels: ready for review

#1317 Only hoist links when more than one granule is present
  web/js/data/ui.js
Labels: under development

#1306 Links in about section open in a new tab/window
  web/pages/about.html
Labels: under development

#1303 Add "wrapX" configuration parameter
  doc/configuration.md
  web/js/map/layerbuilder.js
Labels: under development

#1343 Add .stylelintignore
  .stylelintignore
Labels: ready for review

#1360 Add new readme image
  screenshot.png
Labels: under development

#1318 Add vendor prefix IE11/Edge scrollbar fix for cut off layer list text
  web/css/layers.css
Labels: ready for review

#1364 Fix date rendering between A & B states
  web/js/map/ui.js
Labels: under development
