Repository nasa-gibs/worldview, pull requests merged in 2018-07, with the labels that each got.

#1129 Add a Worldview client identifier in CMR requests
  web/js/data/cmr.js
Labels: under development

#1131 Data download scrollbar overflow
  web/js/data/ui.js
Labels: under development

#1130 Remove warnings when GIBS layers are not used
  tasks/validateOptions.py
Labels: ready for review, technical

#1134 Check for transparent colormap before legend
  tasks/processColormap.py
Labels: under development

#1135 Immutable palette now also applies to continuous values
  web/js/palettes/model.js
Labels: under development

#1142 Add vscode directory and settings
  .vscode/settings.json
Labels: under development

#1138 Break up build bundle transforms to run conditionally depending on dev or production
  tasks/buildJS.js
Labels: bug, under development

#1136 Fixes unset left property of timeline being called 'auto' in some browsers
  web/css/timeline.css
Labels: bug, under development

#1148 Close layer setting dialogs when showing Add Layers modal
  web/js/layers/active.js
Labels: ready for review

#1147 Fix guitar pick and selection draggers from getting cutoff on edges of timeline
  web/css/timeline.css
  web/js/date/timeline.js
Labels: bug, ready for review

#1165 Fix yearly layer not showing proper range
  tasks/processTemporalLayer.py
  web/js/layers/info.js
Labels: under development

#1171 v2.7.0
  package-lock.json
  package.json
Labels: under development
