Repository nasa-gibs/worldview, pull requests merged in 2018-05, with the labels that each got.

#935 Optimize static images
  .gitattributes
  web/images/close-highlight.png
  web/images/close.png
  web/images/data.minus-button.png
  web/images/data.plus-button.png
  web/images/hg-h.png
  web/images/hg.png
  web/images/preview.png
  web/images/tour-fire-location.png
  web/images/tour-map.png
  web/images/tour/layer-picker-1.1.png
  web/images/tour/map-0.7.png
  web/images/tour/timeline-0.7.png
  web/images/tour/timeline-bars-0.7.png
  web/images/tour/timeline-day-buttons-0.7.png
  web/images/tour/timeline-entry-0.7.png
  web/images/tour/timeline-interval-0.7.png
  web/images/tour/timeline-interval-2.0.jpg
  web/images/tour/toolbar-1.4.7.png
  web/images/wv-icons.png
  web/images/wv.layers/accordion.png
  web/images/wv.layers/categories/air-quality.jpg
  web/images/wv.layers/categories/ash-plumes.jpg
  web/images/wv.layers/categories/atmosphere.jpg
  web/images/wv.layers/categories/biosphere.jpg
  web/images/wv.layers/categories/cryosphere.jpg
  web/images/wv.layers/categories/drought.jpg
  web/images/wv.layers/categories/dust-storms.jpg
  web/images/wv.layers/categories/fires.jpg
  web/images/wv.layers/categories/floods.jpg
  web/images/wv.layers/categories/human-dimensions.jpg
  web/images/wv.layers/categories/land-surface.jpg
  web/images/wv.layers/categories/oceans.jpg
  web/images/wv.layers/categories/severe-storms.jpg
  web/images/wv.layers/categories/severe-storms.png
  web/images/wv.layers/categories/shipping.jpg
  web/images/wv.layers/categories/smoke-plumes.jpg
  web/images/wv.layers/categories/spectral-engineering.png
  web/images/wv.layers/categories/terrestrial-hydrosphere.jpg
  web/images/wv.layers/categories/vegetation.jpg
  web/images/wv.layers/show-hide.png
  web/pages/images/gibs.png
Labels: enhancement, under development

#938 Revise PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: under development

#818 Visualize Multi-day Events
  package-lock.json
  package.json
  web/css/events.css
  web/images/natural-events/track-arrow.svg
  web/js/main.js
  web/js/map/ui.js
  web/js/map/util.js
  web/js/natural-events/cluster.js
  web/js/natural-events/markers.js
  web/js/natural-events/model.js
  web/js/natural-events/request.js
  web/js/natural-events/track.js
  web/js/natural-events/ui.js
  web/js/natural-events/util.js
Labels: ready for review

#900 Fix year jump
  web/js/date/timeline-input.js
Labels: ready for review

#944 Show Tour
  web/js/util/browser.js
Labels: ready for review

#949 Fix track disappear when tab changed
  web/js/natural-events/track.js
Labels: ready for review

#974 v2.4.0
  package-lock.json
  package.json
Labels: under development

#967 Stop rotation when mouse pointer moves off the button
  web/js/map/rotation.js
Labels: under development

#966 Update image download parameters on projection change
  web/js/image/panel.js
Labels: under development

#977 Top half of the animation picker is now selectable
  web/css/timeline.css
Labels: under development

#946 fix vertical align for list items in data download - fixes #864
  web/css/dataDownload.css
Labels: bug, under development

#968 Runningdata bug fixes
  web/css/palettes.css
  web/js/map/runningdata.js
  web/js/palettes/legend.js
Labels: ready for review

#969 Increase gif capacity
  package-lock.json
  package.json
  web/ext/gifwriter/gifwriter.js
  web/ext/neuquant/neuquant.js
  web/js/animation/gif-stream.js
  web/js/animation/gif.js
Labels: ready for review

#1014 Image download and GIF bug fixes
  web/js/animation/gif-stream.js
  web/js/animation/gif.js
  web/js/image/panel.js
Labels: ready for review

#1026 v2.5.0
  package-lock.json
  package.json
Labels: under development

#1015 E2e testing foundation
  .travis.yml
  e2e/.eslintrc
  e2e/browserstack.conf.js
  e2e/browserstack.js
  e2e/custom-assertions/elementCountEquals.js
  e2e/environments.js
  e2e/features/animations/animation-test.js
  e2e/features/animations/animations.feature
  e2e/features/animations/animations.gif.feature
  e2e/features/animations/gif-test.js
  e2e/features/animations/querystrings.js
  e2e/features/animations/selectors.js
  e2e/features/events/events-test.js
  e2e/features/events/events.feature
  e2e/features/events/querystrings.js
  e2e/features/layers/layers-test.js
  e2e/features/layers/layers.feature
  e2e/features/layers/querystrings.js
  e2e/features/layers/running-data-test-wip.js
  e2e/features/layers/runningdata.feature
  e2e/features/layers/selectors.js
  e2e/features/tour/tour-test.js
  e2e/features/tour/tour.feature
  e2e/globals.js
  e2e/reuseables/normalize-viewport.js
  e2e/reuseables/skip-tour.js
  e2e/step_definitions/animations.js
  e2e/step_definitions/utility.js
  nightwatch.conf.js
  package-lock.json
  package.json
Labels: ready for review

#1028 Add e2e test documentation #1022
  doc/testing.md
Labels: ready for review, under development
