Repository nasa-gibs/worldview, pull requests merged in 2018-10, with the labels that each got.

#1365 Add libcario to docker build
  Dockerfile
Labels: ready for review

#1289 Event marker hover IE11 CustomEvent fix
  web/js/natural-events/markers.js
Labels: ready for review

#1379 Fix toolbar spacing
  web/css/toolbar.css
Labels: under development

#1383 Check for button on mouseout, remove throttle
  web/js/components/map/ol-coordinates.js
Labels: under development

#1294 Remove additional timezone offset compensation for year zoom timeline
  web/js/date/config.js
Labels: ready for review

#1392 Updates to text and added night layers to storm and fire categories
  config/default/common/config/metadata/modis/CorrectedReflectance.md
  config/default/common/config/metadata/modis/aqua/MODIS_Aqua_CorrectedReflectance_Bands721.md
  config/default/common/config/metadata/modis/aqua/MODIS_Aqua_CorrectedReflectance_TrueColor.md
  config/default/common/config/metadata/modis/terra/MODIS_Terra_CorrectedReflectance_Bands367.md
  config/default/common/config/metadata/modis/terra/MODIS_Terra_CorrectedReflectance_Bands721.md
  config/default/common/config/metadata/modis/terra/MODIS_Terra_CorrectedReflectance_TrueColor.md
  config/default/common/config/metadata/viirs/CorrectedReflectance.md
  config/default/common/config/metadata/viirs/VIIRS_SNPP_CorrectedReflectance_BandsM11-I2-I1.md
  config/default/common/config/metadata/viirs/VIIRS_SNPP_CorrectedReflectance_BandsM3-I3-M11.md
  config/default/common/config/metadata/viirs/VIIRS_SNPP_CorrectedReflectance_TrueColor.md
  config/default/common/config/wv.json/categories/legacy/Severe Storms.json
  config/default/common/config/wv.json/categories/scientific/Land Surface.json
  config/default/common/config/wv.json/layerOrder.json
  config/default/common/config/wv.json/naturalEvents.json
  web/pages/about.html
Labels: under development

#1397 Add new A|B url Parameters to Docs
  doc/url_parameters.md
Labels: under development

#1400 Set html for sidebar event titles
  web/js/components/sidebar/events/event.js
Labels: under development

#1393 Only update checkbox if custom palette is in effect
  web/js/layers/options.js
Labels: under development

#1402 Fix Day of year label in timeline
  web/js/util/util.js
Labels: ready for review

#1409 Highlight full width of long names in product picker
  web/css/layers.css
Labels: ready for review

#1413 Remove README caret
  README.md
Labels: under development

#1398 Optimize rendering of event tracks
  web/js/components/sidebar/products/layer-list.js
  web/js/natural-events/track.js
  web/js/natural-events/ui.js
  web/js/sidebar/ui.js
Labels: under development

#1418 Fix palettes while keeping event track performance #1346 [!mportant]
  web/js/components/sidebar/products/layer-list.js
  web/js/palettes/model.js
Labels: bug, under development

#1417 Fix when newly added base layers can appear at bottom of stack #1412
  web/js/layers/model.js
Labels: bug, under development

#1424 Added OMI UV Aerosol Index layer
  config/default/common/config/metadata/omi/AerosolIndex.md
  config/default/common/config/metadata/omi/OMI_UV_Aerosol_Index.md
  config/default/common/config/wv.json/layerOrder.json
  config/default/common/config/wv.json/layers/omi/OMI_UV_Aerosol_Index.json
  config/default/common/config/wv.json/measurements/Aerosol Index.json
Labels: under development

#1422 Fix custom palettes in compare mode
  web/js/palettes/model.js
Labels: bug, under development

#1430 changed start date for OSCAR layers
  config/default/common/config/metadata/oscar/SeaSurfaceCurrents.md
Labels: ready for review

#1433 Remove dates from console when animation is playing
  web/js/map/precachetile.js
Labels: ready for review

#1435 Added GCOM-C orbit tracks
  config/default/common/colormaps/orbits/GCOM_C_Orbit_Asc.xml
  config/default/common/colormaps/orbits/GCOM_C_Orbit_Dsc.xml
  config/default/common/config/metadata/reference/orbits/GCOM-C.md
  config/default/common/config/metadata/reference/orbits/GCOM_C_Orbit_Asc.md
  config/default/common/config/metadata/reference/orbits/GCOM_C_Orbit_Dsc.md
  config/default/common/config/wv.json/layerOrder.json
  config/default/common/config/wv.json/layers/reference/orbits/GCOM_C_Orbit_Asc.json
  config/default/common/config/wv.json/layers/reference/orbits/GCOM_C_Orbit_Dsc.json
  config/default/common/config/wv.json/measurements/Orbital Track.json
Labels: under development

#1423 added AMSRU2 SWE layers
  config/default/common/config/metadata/amsr2/AMSRU2_Snow_Water_Equivalent_5Day.md
  config/default/common/config/metadata/amsr2/AMSRU2_Snow_Water_Equivalent_Daily.md
  config/default/common/config/metadata/amsr2/AMSRU2_Snow_Water_Equivalent_Monthly.md
  config/default/common/config/wv.json/layerOrder.json
  config/default/common/config/wv.json/layers/amsr2/AMSRU2_Snow_Water_Equivalent_5Day.json
  config/default/common/config/wv.json/layers/amsr2/AMSRU2_Snow_Water_Equivalent_Daily.json
  config/default/common/config/wv.json/layers/amsr2/AMSRU2_Snow_Water_Equivalent_Monthly.json
  config/default/common/config/wv.json/measurements/Snow Water Equivalent.json
Labels: ready for review

#1436 Improve product picker 577
  e2e/features/compare/layer-picker-test.js
  e2e/features/layers/selectors.js
  package-lock.json
  package.json
  web/css/layers.css
  web/css/mobile.css
  web/css/sidebar.css
  web/index.html
  web/js/animation/widget.js
  web/js/app.js
  web/js/components/layer/category-list.js
  web/js/components/layer/category.js
  web/js/components/layer/header.js
  web/js/components/layer/list.js
  web/js/components/layer/measurement-row.js
  web/js/components/layer/product-picker.js
  web/js/components/layer/search-row.js
  web/js/components/sidebar/sidebar.js
  web/js/components/util/checkbox.js
  web/js/layers/modal.js
  web/js/sidebar/ui.js
Labels: under development

#1438 Add moment.js as devDependency for builds
  package-lock.json
  package.json
Labels: under development

#1452 Added ISS LIS Layers
  config/default/common/config/metadata/iss/LIS_ISS_Flash_Count.md
  config/default/common/config/metadata/iss/LIS_ISS_Flash_Radiance.md
  config/default/common/config/metadata/iss/LightningFlashCount&Radiance.md
  config/default/common/config/wv.json/layerOrder.json
  config/default/common/config/wv.json/layers/iss/LIS_ISS_Flash_Count.json
  config/default/common/config/wv.json/layers/iss/LIS_ISS_Flash_Radiance.json
  config/default/common/config/wv.json/measurements/Lightning.json
  config/default/common/config/wv.json/products/iss/isslis_p0_nrt.json
Labels: under development
