Repository nasa-gibs/worldview, pull requests merged in 2018-12, with the labels that each got.

#1530 Added IMERG descriptions
  config/default/common/config/metadata/multi-mission/imerg/IMERG_Rain_Rate.md
  config/default/common/config/metadata/multi-mission/imerg/IMERG_Snow_Rate.md
  config/default/common/config/metadata/multi-mission/imerg/Precipitation.md
Labels: testing

#1534 v2.11.0
  package-lock.json
  package.json
Labels: under development

#1520 Add condition to check for swipe-line node before performing window resize functions
  web/js/map/compare/swipe.js
Labels: ready for review

#1513 Show/select first valid available layer measurement in product picker
  web/js/components/layer/measurement-row.js
Labels: ready for review

#1518 Check for dialog to be initialized prior to closing
  web/js/layers/info.js
  web/js/layers/options.js
Labels: ready for review

#1519 Add status flag to prevent multiple GIFs from being creating while one is in progress
  web/js/animation/gif.js
Labels: ready for review

#1533 Date advancement problem in comparison mode
  web/css/timeline.css
  web/js/date/timeline-input.js
Labels: ready for review

#1535 Fix image download size adjuster
  web/css/image.css
  web/index.html
  web/js/image/panel.js
Labels: bug, ready for review

#1508 Migrate to Font Awesome v5
  package-lock.json
  package.json
  web/css/anim.widget.css
  web/css/jquery-ui-override.css
  web/css/layers.css
  web/css/link.css
  web/css/map.css
  web/css/sidebar-panel.css
  web/js/app.js
  web/js/components/animation-widget/animation-widget.js
  web/js/components/layer/search-row.js
  web/js/components/share/links.js
  web/js/components/sidebar/events/event.js
  web/js/components/sidebar/products/layer.js
  web/js/data/ui.js
  web/js/link/ui.js
  web/js/map/compare/swipe.js
  web/js/map/rotation.js
  web/js/natural-events/ui.js
  web/js/projection/ui.js
  web/js/ui/ui.js
  web/pages/tour.html
Labels: ready for review

#1536 Add cssnext postcss plugin to webpack build
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement, under development

#1529 Dual customs
  package-lock.json
  package.json
  web/css/checkbox.css
  web/css/layers.css
  web/css/palettes.css
  web/css/sidebar.css
  web/js/app.js
  web/js/components/layer/product-picker/category-list.js
  web/js/components/layer/product-picker/category.js
  web/js/components/layer/product-picker/header.js
  web/js/components/layer/product-picker/list.js
  web/js/components/layer/product-picker/measurement-layer-row.js
  web/js/components/layer/product-picker/measurement-row.js
  web/js/components/layer/product-picker/product-picker.js
  web/js/components/layer/product-picker/search-row.js
  web/js/components/layer/settings/opacity.js
  web/js/components/layer/settings/palette.js
  web/js/components/layer/settings/settings.js
  web/js/components/layer/settings/threshold.js
  web/js/components/sidebar/products/layer-list.js
  web/js/components/sidebar/products/layer.js
  web/js/components/sidebar/products/legend.js
  web/js/components/sidebar/provider.js
  web/js/components/sidebar/sidebar.js
  web/js/components/util/checkbox.js
  web/js/components/util/range-input.js
  web/js/layers/modal.js
  web/js/layers/options.js
  web/js/palettes/model.js
  web/js/palettes/util.js
  web/js/sidebar/ui.js
Labels: ready for review

#1544 Prevent Data Download and Comparison modes from being loaded in mobile
  web/js/compare/model.js
  web/js/data/model.js
Labels: ready for review

#1555 Add Missing fa icon
  web/js/components/sidebar/products/layer.js
Labels: under development

#1542 Pinch zoom on event icon zooms browser
  web/js/components/sidebar/sidebar.js
  web/js/date/timeline.js
  web/js/natural-events/markers.js
  web/js/util/browser.js
  web/js/util/util.js
Labels: under development

#1545 A|B Additions
  web/css/compare.css
  web/css/sidebar.css
  web/images/ab-modes.png
  web/images/ab-picks.png
  web/images/ab-tabs.png
  web/js/app.js
  web/js/compare/ui.js
  web/js/components/compare/opacity-slider.js
  web/js/components/sidebar/mode-selection.js
  web/js/date/model.js
  web/js/map/compare/opacity.js
  web/js/map/compare/swipe.js
Labels: under development

#1558 Add colormaps
  config/default/common/config/palettes-custom.json/cb_safe_1.json
  config/default/common/config/palettes-custom.json/cb_safe_2.json
  config/default/common/config/palettes-custom.json/divergent_1.json
  config/default/common/config/palettes-custom.json/divergent_2.json
  config/default/common/config/palettes-custom.json/green_2.json
  config/default/common/config/palettes-custom.json/purple_3.json
  config/default/common/config/palettes-custom.json/rainbow_3.json
  config/default/common/config/wv.json/paletteOrder.json
  tasks/csv2colormap.js
  web/pages/about.html
Labels: under development

#1556 Format GIF addFrame to upload to Twitter
  web/ext/gifwriter/gifwriter.js
Labels: under development

#1560 Update orbit track layer names in measurements
  config/default/common/config/wv.json/measurements/Aerosol Albedo.json
  config/default/common/config/wv.json/measurements/Aerosol Index.json
  config/default/common/config/wv.json/measurements/Aerosol Optical Depth.json
  config/default/common/config/wv.json/measurements/Brightness Temperature.json
  config/default/common/config/wv.json/measurements/Carbon Monoxide.json
  config/default/common/config/wv.json/measurements/Chlorophyll A.json
  config/default/common/config/wv.json/measurements/Cloud Effective Radius.json
  config/default/common/config/wv.json/measurements/Cloud Fraction.json
  config/default/common/config/wv.json/measurements/Cloud Liquid Water.json
  config/default/common/config/wv.json/measurements/Cloud Multi Layer Flag.json
  config/default/common/config/wv.json/measurements/Cloud Optical Thickness.json
  config/default/common/config/wv.json/measurements/Cloud Phase.json
  config/default/common/config/wv.json/measurements/Cloud Pressure.json
  config/default/common/config/wv.json/measurements/Cloud Top Height.json
  config/default/common/config/wv.json/measurements/Cloud Top Temperature.json
  config/default/common/config/wv.json/measurements/Cloud Water Path.json
  config/default/common/config/wv.json/measurements/Corrected Reflectance.json
  config/default/common/config/wv.json/measurements/Dust.json
  config/default/common/config/wv.json/measurements/Faraday Rotation.json
  config/default/common/config/wv.json/measurements/Fires and Thermal Anomalies.json
  config/default/common/config/wv.json/measurements/Land Surface Reflectance.json
  config/default/common/config/wv.json/measurements/Land Surface Temperature.json
  config/default/common/config/wv.json/measurements/Mammal Richness.json
  config/default/common/config/wv.json/measurements/Nitric Acid.json
  config/default/common/config/wv.json/measurements/Nitrogen Dioxide.json
  config/default/common/config/wv.json/measurements/Nitrous Oxide.json
  config/default/common/config/wv.json/measurements/Orbital Track.json
  config/default/common/config/wv.json/measurements/Ozone.json
  config/default/common/config/wv.json/measurements/Precipitation Estimate.json
  config/default/common/config/wv.json/measurements/Precipitation Rate.json
  config/default/common/config/wv.json/measurements/Relative Humidity.json
  config/default/common/config/wv.json/measurements/Sea Ice Brightness Temperature.json
  config/default/common/config/wv.json/measurements/Sea Ice.json
  config/default/common/config/wv.json/measurements/Sigma0.json
  config/default/common/config/wv.json/measurements/Soil Moisture.json
  config/default/common/config/wv.json/measurements/Sulfur Dioxide.json
  config/default/common/config/wv.json/measurements/Temperature.json
  config/default/common/config/wv.json/measurements/Water Vapor.json
  config/default/common/config/wv.json/measurements/Wind Speed.json
  tasks/validateOptions.py
Labels: under development
