Repository nasa-gibs/worldview, pull requests merged in 2018-11, with the labels that each got.

#1445 Product Picker Font Fixes
  web/css/layers.css
Labels: ready for review

#1474 Add autoFocus when not using a touch device
  web/js/components/layer/header.js
  web/js/components/layer/product-picker.js
Labels: ready for review

#1475 Make category background images work in Edge
  web/js/components/layer/category.js
Labels: ready for review

#1448 Add stylelint to tests and fix css lint errors
  package.json
  web/css/layers.css
Labels: bug, ready for review

#1476 Fix additional stylelint errors
  web/css/layers.css
Labels: bug

#1477 Redo sort measurement source order
  web/js/components/layer/measurement-row.js
Labels: ready for review

#1479 Rename exceedLength to overflow
  web/js/data/map.js
Labels: under development

#1485 Override body position to static
  web/css/jquery-ui-override.css
Labels: under development

#1478 Fix sub-daily check
  web/js/map/layerbuilder.js
Labels: under development

#1487 Removed inactive tag and updated end date
  config/default/common/config/metadata/omi/UVRadiation.md
  config/default/common/config/wv.json/layers/omi/OMI_UV_Erythemal_Daily_Dose.json
  config/default/common/config/wv.json/layers/omi/OMI_UV_Erythemal_Dose_Rate.json
  config/default/common/config/wv.json/layers/omi/OMI_UV_Index.json
Labels: ready for review

#1483 Make layer add/remove faster
  web/js/components/layer/header.js
  web/js/components/layer/measurement-layer-row.js
  web/js/components/layer/measurement-row.js
  web/js/components/layer/product-picker.js
  web/js/components/sidebar/footer-content.js
  web/js/components/sidebar/provider.js
  web/js/components/util/button.js
  web/js/components/util/checkbox.js
  web/js/date/config.js
  web/js/date/timeline.js
  web/js/layers/modal.js
  web/js/layers/model.js
  web/js/sidebar/ui.js
Labels: ready for review

#1482 Use ol drag listener to update spy
  web/js/map/compare/spy.js
Labels: bug

#1489 Fix IE11 scrollbars
  web/css/jquery-ui-override.css
  web/css/reset.css
  web/js/app.js
Labels: ready for review

#1502 Fix timeline data bar colors not updating
  web/js/date/timeline.js
Labels: under development

#1500 Remove GA code for GTM upgrade
  config/default/common/features.json
  web/js/app.js
  web/js/components/util/google-analytics.js
Labels: under development

#1504 Remove date key for static layers
  doc/configuration.md
  web/js/map/layerbuilder.js
Labels: under development

#1514 added data download for SMAP Freeze/Thaw
  config/default/common/config/wv.json/layers/smap/SMAP_L3_Passive_Day_Freeze_Thaw.json
  config/default/common/config/wv.json/layers/smap/SMAP_L3_Passive_Enhanced_Day_Freeze_Thaw.json
  config/default/common/config/wv.json/layers/smap/SMAP_L3_Passive_Enhanced_Night_Freeze_Thaw.json
  config/default/common/config/wv.json/layers/smap/SMAP_L3_Passive_Night_Freeze_Thaw.json
Labels: under development

#1512 fixed citation and event layers
  config/default/common/config/wv.json/naturalEvents.json
  web/pages/about.html
Labels: under development
