Repository nasa-gibs/worldview, pull requests merged in 2019-01, with the labels that each got.

#1563 Allow A|B alert to close
  web/js/compare/ui.js
Labels: under development

#1567 Fix broken E2E tests
  e2e/features/compare/layer-dialog-test.js
  e2e/features/compare/layer-picker-test.js
  e2e/features/events/events-test.js
  e2e/features/notifications/notify-test.js
  e2e/reuseables/selectors.js
  web/js/components/animation-widget/animation-widget.js
  web/js/components/layer/settings/settings.js
Labels: testing, under development

#1566 Reapply event-related layers on second selection
  config/default/common/config/wv.json/naturalEvents.json
  tasks/validateOptions.py
  web/js/map/animate.js
  web/js/natural-events/ui.js
  web/js/sidebar/ui.js
Labels: under development

#1571 Normalize range input
  package-lock.json
  package.json
  web/css/anim.widget.css
  web/css/compare.css
  web/css/layers.css
  web/css/palettes.css
  web/js/app.js
  web/js/components/animation-widget/animation-widget.js
  web/js/components/compare/opacity-slider.js
  web/js/components/layer/settings/opacity.js
  web/js/components/layer/settings/threshold.js
  web/js/components/util/range-input.js
Labels: ready for review

#1574 Prevent highlighting of custom palettes
  web/css/util.css
  web/js/components/layer/settings/palette.js
Labels: ready for review

#1579 Make settings unmount before reloading new settings modal
  e2e/features/layers/layers-test.js
  e2e/features/layers/options-test.js
  web/js/components/layer/settings/opacity.js
  web/js/components/layer/settings/settings.js
  web/js/layers/options.js
Labels: bug, ready for review

#1583 Fix spacing between dual palette selection legend and image
  web/css/layers.css
Labels: ready for review

#1584 Fix yOffset issue for timeline tick hover
  web/css/timeline.css
  web/js/components/range-selection/dragger-range.js
  web/js/components/range-selection/dragger.js
  web/js/date/compare-picks.js
  web/js/date/timeline-pick.js
  web/js/date/timeline.js
Labels: under development

#1588 Data download for ASMRU Sea ice concentration layers
  config/default/common/config/wv.json/layers/amsr2/AMSRU2_Sea_Ice_Concentration_12km.json
  config/default/common/config/wv.json/layers/amsr2/AMSRU2_Sea_Ice_Concentration_25km.json
  config/default/common/config/wv.json/products/amsr2/AU_SI12.json
  config/default/common/config/wv.json/products/amsr2/AU_SI25.json
Labels: under development

#1593 Change to moveBefore/pushToBottom instead of replacing layer list
  web/js/components/sidebar/products/layer-list.js
  web/js/layers/model.js
Labels: under development

#1589 Add Snapshots support to GIF
  web/js/animation/gif.js
  web/js/components/animation-widget/gif-panel-grid.js
  web/js/components/animation-widget/gif-panel.js
Labels: ready for review

#1595 Always show dateline when using tablets
  web/js/components/dateline/dateline.js
Labels: quickfix, ready for review

#1596 Remove alerts from tablets
  web/js/compare/ui.js
  web/js/natural-events/ui.js
Labels: ready for review

#1597 Larger slider handles (Draggers)
  web/css/anim.widget.css
  web/css/compare.css
  web/css/layers.css
  web/css/rc-slider-overrides.css
  web/js/app.js
  web/js/components/animation-widget/animation-widget.js
Labels: ready for review

#1599 Prevent highlight of text while using slider
  web/css/rc-slider-overrides.css
Labels: under development

#1604 Added measurement for protected areas
  config/default/common/config/metadata/wdpa/ProtectedAreas.md
  config/default/common/config/wv.json/categories/legacy/All.json
  config/default/common/config/wv.json/categories/scientific/All.json
  config/default/common/config/wv.json/categories/scientific/Human Dimensions.json
  config/default/common/config/wv.json/measurements/Protected Areas.json
Labels: under development

#1611 Switch sourceMetaData state key to use source description in place of id
  web/js/components/layer/product-picker/list.js
  web/js/components/layer/product-picker/measurement-row.js
Labels: under development

#1616 v2.12.0
  package-lock.json
  package.json
Labels: under development
