Repository nasa-gibs/worldview, pull requests merged in 2019-07, with the labels that each got.

#1781 V3.0 bug fixes
  e2e/features/animations/animation-test.js
  e2e/features/animations/gif-test.js
  e2e/features/compare/compare-test.js
  e2e/features/compare/layer-dialog-test.js
  e2e/features/compare/timeline-test.js
  e2e/features/data-download/data-download-test.js
  e2e/globals.js
  e2e/reuseables/selectors.js
  web/css/modal.css
  web/css/tour.css
  web/js/components/image-download/notify.js
  web/js/components/layer/info/info.js
  web/js/components/layer/product-picker/header.js
  web/js/components/layer/product-picker/product-picker.js
  web/js/components/timeline/timeline-controls/animation-button.js
  web/js/components/timeline/timeline-controls/axis-timescale-change-tooltip.js
  web/js/containers/animation-widget.js
  web/js/containers/gif.js
  web/js/containers/sidebar/footer-content.js
  web/js/containers/sidebar/layer-list.js
  web/js/containers/sidebar/layer.js
  web/js/containers/timeline/timeline.js
  web/js/containers/toolbar.js
  web/js/location.js
  web/js/map/data/map.js
  web/js/map/data/ui.js
  web/js/map/natural-events/ui.js
  web/js/map/ui.js
  web/js/modules/compare/util.js
  web/js/modules/data/util.js
  web/js/modules/map/reducers.js
  web/js/modules/sidebar/util.js
Labels: ready for review

#1801 v3.0 SIT bug fixes #2
  web/css/layers.css
  web/js/app.js
  web/js/components/alert/alert.js
  web/js/components/image-download/panel.js
  web/js/components/layer/info/info.js
  web/js/components/tour/alert.js
  web/js/components/util/alert.js
  web/js/components/util/image-crop.js
  web/js/containers/image-download.js
  web/js/containers/info.js
  web/js/containers/sidebar/layer.js
  web/js/containers/tour.js
  web/js/location.js
  web/js/map/data/ui.js
  web/js/map/model.js
  web/js/map/ui.js
  web/js/modules/animation/constants.js
  web/js/modules/animation/reducer.test.js
  web/js/modules/animation/reducers.js
  web/js/modules/combine-reducers.js
  web/js/modules/data/util.js
  web/js/modules/image-download/actions.js
  web/js/modules/image-download/constants.js
  web/js/modules/image-download/reducers.js
  web/js/modules/key-press/actions.js
  web/js/modules/layers/actions.js
  web/js/modules/layers/util.js
  web/js/modules/map/constants.js
  web/js/modules/map/reducers.js
  web/js/modules/map/util.js
  web/js/modules/palettes/util.js
  web/js/modules/projection/util.js
  web/js/modules/sidebar/util.js
  web/js/modules/tour/util.js
Labels: ready for review

#1828 V3.0 bug fixes #3
  e2e/features/events/events-test.js
  e2e/features/image-download/formats-test.js
  e2e/features/image-download/resolutions4326-test.js
  e2e/features/image-download/unsupported-test.js
  e2e/features/layers/layers-test.js
  e2e/features/layers/options-test.js
  e2e/features/notifications/notify-test.js
  e2e/globals.js
  e2e/reuseables/image-download.js
  e2e/reuseables/selectors.js
  e2e/reuseables/switch-projection.js
  e2e/reuseables/zoom.js
  web/css/button.css
  web/css/dataDownload.css
  web/css/timeline.css
  web/css/toolbar.css
  web/js/components/animation-widget/play-queue.js
  web/js/components/image-download/panel.js
  web/js/components/layer/product-picker/header.js
  web/js/components/layer/product-picker/product-picker.js
  web/js/components/timeline/timeline-controls/animation-button.js
  web/js/components/util/alert.js
  web/js/components/util/list.js
  web/js/containers/sidebar/data.js
  web/js/containers/sidebar/layer.js
  web/js/containers/sidebar/sidebar.js
  web/js/containers/toolbar.js
  web/js/map/data/map.js
  web/js/map/data/ui.js
  web/js/map/layerbuilder.js
  web/js/map/ui.js
  web/js/modules/image-download/reducers.js
  web/js/modules/layers/selectors.js
  web/js/modules/modal/actions.js
  web/js/modules/sidebar/actions.js
  web/js/modules/sidebar/constants.js
  web/js/modules/sidebar/reducers.js
Labels: ready for review

#1851 Data download fixes
  web/js/containers/sidebar/data.js
  web/js/map/data/ui.js
  web/js/modules/data/selectors.js
Labels: ready for review

#1853 Check data state at time of granule swath removal for currently selected granules
  web/js/map/data/ui.js
Labels: ready for review

#1860 Fix condition to change dragger position on natural event date change
  web/js/components/timeline/timeline-axis/timeline-axis.js
  web/js/components/timeline/timeline-draggers/dragger-container.js
Labels: ready for review

#1856 Adjust toolbar modal responsive positions
  web/css/toolbar.css
  web/js/containers/toolbar.js
Labels: ready for review

#1863 Add missing vector-filter utilities and actions
  web/js/modules/vector-styles/selectors.js
  web/js/modules/vector-styles/util.js
Labels: ready for review

#1857 Prevent downloading rotated images
  web/js/map/rotation.js
Labels: quickfix, ready for review

#1870 Update v3.0 tour modal styles to match v2.17
  web/css/tour.css
Labels: bug

#1879 Make palette color bar extend full width in mobile
  web/css/palettes.css
  web/js/components/sidebar/paletteLegend.js
  web/js/containers/sidebar/layer.js
Labels: ready for review

#1878 Make mobile send feedback via email
  web/js/containers/info.js
Labels: ready for review

#1889 Fix IE11 selecting other DOM elements while dragging swiper in compare mode and cursor
  web/css/compare.css
Labels: enhancement

#1887 Fix event track points not setting date correctly after clicking a supercluster (or switching sidebar tabs)
  web/js/map/natural-events/track.js
Labels: ready for review

#1886 Add colons to browser and version in issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#1877 Animation start/end date updates
  web/js/fixtures.js
  web/js/modules/animation/actions.js
  web/js/modules/animation/actions.test.js
  web/js/modules/animation/reducer.test.js
  web/js/modules/animation/reducers.js
  web/js/modules/animation/util.js
Labels: ready for review

#1897 Fix vector style not being applied when changing date
  web/js/map/ui.js
Labels: bug

#1896 Fix event tracks disappearing when switching projections
  web/js/map/natural-events/ui.js
Labels: ready for review

#1892 Fix supercluster overlays sometimes not being removed when zooming in
  web/js/map/natural-events/track.js
Labels: ready for review

#1890 Fix image download and GIF download size problems
  e2e/features/animation/animation-test.js
  e2e/features/animation/gif-test.js
  e2e/features/image-download/initial-state-test.js
  e2e/reuseables/selectors.js
  web/js/components/animation-widget/gif-panel-grid.js
  web/js/components/animation-widget/gif-panel.js
  web/js/components/image-download/panel.js
  web/js/containers/gif.js
  web/js/util/util.js
Labels: ready for review

#1907 Prevent ctrl or cmd plus left/right timeline arrows from invoking change date function
  web/js/containers/timeline/timeline.js
Labels: ready for review

#1910 Update event track projection handling
  web/js/containers/sidebar/events.js
  web/js/map/natural-events/track.js
  web/js/map/natural-events/ui.js
  web/js/modules/natural-events/selectors.js
Labels: ready for review

#1900 Prevent data-download click while animating to event #1883
  web/js/components/sidebar/nav/nav-case.js
  web/js/containers/sidebar/sidebar.js
  web/js/map/natural-events/ui.js
  web/js/modules/natural-events/actions.js
  web/js/modules/natural-events/constants.js
  web/js/modules/natural-events/reducers.js
Labels: ready for review

#1913 Fix animation speed in gifs
  web/js/modules/animation/selectors.js
Labels: ready for review

#1915 Fix showing/hiding date stamp on gifs
  web/js/components/animation-widget/gif-panel.js
  web/js/containers/gif.js
Labels: ready for review

#1919 Animation breaks when permalink has ab='on' without animation start and end dates
  web/js/app.js
  web/js/modules/animation/util.js
  web/js/modules/combine-reducers.js
Labels: ready for review

#1917 Update grid axis drag sentinel count with boundsDiff taken into account
  web/js/components/timeline/timeline-axis/timeline-axis.js
  web/js/containers/timeline/timeline.js
Labels: UAT, ready for review

#1926 Wildfires tour bug UAT v3.0
  web/js/containers/timeline/timeline.js
  web/js/modules/date/util.js
Labels: UAT, ready for review
