Repository nasa-gibs/worldview, pull requests merged in 2019-08, with the labels that each got.

#1924 Event click mobile device [v3.1]
  web/js/map/natural-events/markers.js
Labels: ready for review

#1957 Refactor import to fix console error
  web/js/main.js
Labels: ready for review

#1947 Add options to fix copy-to-clipboard copied text format
  web/js/containers/share.js
Labels: bug, ready for review

#1970 Update postcss / cssnano dependencies & webpack config
  package-lock.json
  package.json
  webpack.config.js
Labels: ready for review

#1955 Prevent event track from showing up when not in events mode
  web/js/map/natural-events/track.js
Labels: bug

#1979 Optimize travis-ci builds
  .travis.yml
Labels: ready for review

#1967 Optimize static imagery for page load time savings
  config/default/common/config/metadata/stories/california_british_columbia_wildfires_summer_2018/westcoastfires_background.png
  config/default/common/config/metadata/stories/camp_fire_november_2018/background.png
  config/default/common/config/metadata/stories/explore_the_earth_at_night/background.png
  config/default/common/config/metadata/stories/fires_overview_2019/fires_overview.png
  config/default/common/config/metadata/stories/hurricane_florence_september_2018/background.png
  config/default/common/config/metadata/stories/hurricane_maria_september_2017/background.png
  config/default/common/config/metadata/stories/larsen_c_ice_shelf_iceberg_a68a_july_2017/background.png
  config/default/common/config/metadata/stories/pine_island_glacier_icebergb46_nov_2018/b46iceberg_background.png
  config/default/common/config/metadata/stories/saharan_dust_storms_2018/background.png
  config/default/common/config/metadata/stories/shrinking_aral_sea_2001_2018/background.png
  config/default/common/config/metadata/stories/sinabung_volcano_eruption_february_2018/background.png
  config/default/common/config/metadata/stories/snow_in_lesotho_south_africa_august_2018/background.png
  config/default/common/config/metadata/stories/snow_in_lesotho_south_africa_august_2018/backgroundHover.gif
  config/default/common/config/metadata/stories/sunglint/sunglint.png
  config/default/common/config/metadata/stories/swath_gaps/swath_gaps_background.png
  config/default/common/config/metadata/stories/tc_idai_march_2019/TCIdal_background.png
  config/default/common/config/metadata/stories/worldview_intro/wv_background.png
  web/images/ab-modes.png
  web/images/ab-picks.png
  web/images/ab-tabs.png
  web/images/preview.png
Labels: enhancement

#1988 Use zeroed times for data download time filtering
  web/js/map/data/results.js
Labels: ready for review

#2014 Render metadata tooltips as HTML
  web/js/components/vector-metadata/tooltip.js
Labels: ready for review

#2018 Fix layerIds that have dot notation to allow object property selection
  web/js/containers/sidebar/layer.js
  web/js/modules/layers/selectors.js
  web/js/modules/palettes/selectors.js
Labels: ready for review

#2013 Fix vector layer ids with periods breaking vector styles/data
  tasks/processVectorData.py
  tasks/processVectorStyles.py
Labels: ready for review

#2019 Bump browserstack-capabilities from 0.4.0 to 0.7.0
  package-lock.json
  package.json
Labels: external dependency, ready for review

#2021 fix eslint errors
  web/js/containers/sidebar/layer.js
  web/js/modules/layers/selectors.js
Labels: ready for review

#2044 Limit subdaily date range to one hour before and after current date
  web/js/map/datelinebuilder.js
  web/js/util/util.js
Labels: ready for review

#2050 End tour to set isActive as false and close dialog
  web/js/containers/tour.js
Labels: SIT, bug

#2037 Show event title on hover
  web/js/map/natural-events/markers.js
Labels: quickfix, ready for review

#2059 Add projection param to all stepLinks for new fires tour
  config/default/common/config/wv.json/stories/wildfire/fires_overview_2019.json
Labels: ready for review

#2061 Make sure we check to see if localStorage is accessible before trying to access it
  web/js/containers/sidebar/events.js
  web/js/modules/notifications/util.js
Labels: ready for review

#2065 Scroll layer descriptions
  web/css/layers.css
  web/js/containers/sidebar/layer.js
Labels: ready for review

#2088 Fix CI build errors related to python3
  .travis.yml
Labels: bug
